
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-docker_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
          - "5433:5432"
  
  backend:
    build:
      context: Backend
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./Backend:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME:-docker_db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-rostgres}
      DB_HOST: ${DB_HOST_DC:-db}
      DB_PORT: ${DB_PORT:-5432}
    command:
      - sh
      - -c
      - "python manage.py migrate && python manage.py runserver"

  tests:
    build:
      context: Backend
      target: tests
    volumes:
      - ./Backend:/app
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME:-docker_db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_HOST: ${DB_HOST_DC:-db}
      DB_PORT: ${DB_PORT:-5432}
    command:
      - sh
      - -c
      - "python manage.py migrate && pytest"

  pip-compile-django:
    build:
      context: Backend
      target: tests
    volumes:
      - ./Backend:/app
    working_dir: /app
    entrypoint: ["sh", "-c"]
    command:
      - pip-compile --strip-extras requirements.in
      - pip-compile --strip-extras requirements_tests.in

volumes:
  postgres_data:
