# Generated by Django 5.1.7 on 2025-06-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="column",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="task",
            name="comments",
            field=models.TextField(blank=True),
        ),
    ]
