# Generated by Django 5.1.7 on 2025-06-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0004_task_author_task_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assignee",
        ),
    ]
