name: AI Code Review

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  ai_review:
    runs-on: ubuntu-latest
    name: AI PR Review
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run CodeRabbit AI Reviewer
        uses: coderabbitai/openai-pr-reviewer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          openai_light_model: gpt-3.5-turbo
          openai_heavy_model: gpt-3.5-turbo
          review_comment_lgtm: false
          review_simple_changes: true
          summarize: true
          system_message: >
            You are a technical code reviewer. Write briefly, clearly and strictly to the point. Make comments only on significant issues (code style, errors, architecture).
