name: PR Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run CodeRabbit Review with fallback
        id: codereview
        continue-on-error: true
        uses: coderabbitai/openai-pr-reviewer@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_base_url: https://api.openai.com/v1
          openai_light_model: gpt-4o
          openai_heavy_model: gpt-4o
          openai_model_temperature: 0.05
          system_message: |
            You are a technical code reviewer. Write briefly, clearly and strictly to the point. Make comments only on significant issues (code style, errors, architecture).
          language: en-US
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Fallback to GPT-3.5 if GPT-4o fails
        if: failure()
        uses: coderabbitai/openai-pr-reviewer@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_base_url: https://api.openai.com/v1
          openai_light_model: gpt-3.5-turbo
          openai_heavy_model: gpt-3.5-turbo
          openai_model_temperature: 0.05
          system_message: |
            You are a technical code reviewer. Write briefly, clearly and strictly to the point. Make comments only on significant issues (code style, errors, architecture).
          language: en-US
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
